AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  backend

  Sample SAM Template for backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      
      Environment:
        Variables:
          PRODUCT_DB_BUCKET: !Ref ProductDatabaseBucket
          OPENAI_API_KEY_PARAM: /ad-forge/openai-api-key
          ELEVENLABS_API_KEY_PARAM: /ad-forge/elevenlabs-api-key 
          SHOTSTACK_API_KEY_PARAM: /ad-forge/shotstack-api-key 
      # This section gives our function permission to read from the S3 bucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref ProductDatabaseBucket
        - S3WritePolicy: # <-- Add this policy to allow writing the audio file
            BucketName: !Ref ProductDatabaseBucket
        - SSMReadPolicy:
            ParameterName: /ad-forge/openai-api-key
        - SSMReadPolicy: # <-- Add this policy
            ParameterName: /ad-forge/elevenlabs-api-key
        - SSMReadPolicy: # <-- Add this policy
            ParameterName: /ad-forge/shotstack-api-key
        

  ProductDatabaseBucket:
    Type: AWS::S3::Bucket
    Properties:
      # IMPORTANT: Replace this with the unique bucket name you created
      BucketName: ad-forge-database-amg-2025

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World 
      function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
