AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Final SAM Template for Ad-Forge Backend

Globals:
  Function:
    Timeout: 900 # Set to max for long video renders
    LoggingConfig:
      LogFormat: JSON

Resources:
  AdForgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.13 # Using a stable, supported runtime
      Architectures:
        - x86_64
      MemorySize: 512
      Events:
        AdForgeApi:
          Type: Api
          Properties:
            Path: /forge
            Method: post
      Environment:
        Variables:
          # We now directly provide the name of the existing bucket
          PRODUCT_DB_BUCKET: "ad-forge-database-amg-2025"
          OPENROUTER_API_KEY_PARAM: /ad-forge/openrouter-api-key
          ELEVENLABS_API_KEY_PARAM: /ad-forge/elevenlabs-api-key
          SHOTSTACK_API_KEY_PARAM: /ad-forge/shotstack-api-key
          HF_TOKEN_PARAM: /ad-forge/hf-token
      Policies:
        # Policies now refer directly to the existing bucket name
        - S3ReadPolicy:
            BucketName: "ad-forge-database-amg-2025"
        - S3WritePolicy:
            BucketName: "ad-forge-database-amg-2025"
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource:
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ad-forge/hf-token"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ad-forge/elevenlabs-api-key"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ad-forge/shotstack-api-key"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ad-forge/openrouter-api-key"

  # The 'ProductDatabaseBucket' resource block has been completely removed
  # to prevent the "already exists" error.

Outputs:
  AdForgeApi:
    Description: "API Gateway endpoint URL for Ad-Forge function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/forge/"
  AdForgeFunctionArn:
    Description: "Ad-Forge Lambda Function ARN"
    Value: !GetAtt AdForgeFunction.Arn
  AdForgeFunctionIamRoleArn:
    Description: "Implicit IAM Role created for Ad-Forge function"
    Value: !GetAtt AdForgeFunctionRole.Arn