AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Final, Asynchronous SAM Template for Ad-Forge Backend (Hugging Face Model)

Globals:
  Function:
    Runtime: python3.11
    Architectures:
      - x86_64
    LoggingConfig:
      LogFormat: JSON

Resources:
  # The DynamoDB table to track job status
  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: jobId
          AttributeType: S
      KeySchema:
        - AttributeName: jobId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Lambda Function #1: Starts the job
  ForgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: forge_function/
      Handler: app.lambda_handler
      Timeout: 29
      MemorySize: 256
      Environment:
        Variables:
          JOBS_TABLE_NAME: !Ref JobsTable
          WORKER_FUNCTION_NAME: !Ref WorkerFunction
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
        - LambdaInvokePolicy:
            FunctionName: !Ref WorkerFunction
      Events:
        ForgeApi:
          Type: Api
          Properties:
            Path: /forge
            Method: post

  # Lambda Function #2: The long-running worker
  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: worker_function/
      Handler: app.lambda_handler
      Timeout: 900 # 15 minutes
      MemorySize: 1024
      Environment:
        Variables:
          JOBS_TABLE_NAME: !Ref JobsTable
          PRODUCT_DB_BUCKET: "ad-forge-database-amg-2025"
          # --- CORRECTED KEYS for Hugging Face Workflow ---
          OPENROUTER_API_KEY_PARAM: /ad-forge/openrouter-api-key
          HF_TOKEN_PARAM: /ad-forge/hf-token
          ELEVENLABS_API_KEY_PARAM: /ad-forge/elevenlabs-api-key
          SHOTSTACK_API_KEY_PARAM: /ad-forge/shotstack-api-key
      Policies:
        - S3ReadPolicy:
            BucketName: "ad-forge-database-amg-2025"
        - S3WritePolicy:
            BucketName: "ad-forge-database-amg-2025"
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource:
              # --- CORRECTED RESOURCES for Hugging Face Workflow ---
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ad-forge/openrouter-api-key"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ad-forge/hf-token"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ad-forge/elevenlabs-api-key"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ad-forge/shotstack-api-key"

  # Lambda Function #3: Checks the job status
  StatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: status_function/
      Handler: app.lambda_handler
      Timeout: 29
      MemorySize: 256
      Environment:
        Variables:
          JOBS_TABLE_NAME: !Ref JobsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref JobsTable
      Events:
        StatusApi:
          Type: Api
          Properties:
            Path: /status/{jobId}
            Method: get

Outputs:
  AdForgeApi:
    Description: "API Gateway base endpoint URL for the Ad-Forge service"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"