AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Final, Asynchronous SAM Template for Ad-Forge Backend (Hugging Face
  Model)

  '
Globals:
  Function:
    Runtime: python3.11
    Architectures:
    - x86_64
    LoggingConfig:
      LogFormat: JSON
Resources:
  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: jobId
        AttributeType: S
      KeySchema:
      - AttributeName: jobId
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  ForgeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ForgeFunction
      Handler: app.lambda_handler
      Timeout: 29
      MemorySize: 256
      Environment:
        Variables:
          JOBS_TABLE_NAME:
            Ref: JobsTable
          WORKER_FUNCTION_NAME:
            Ref: WorkerFunction
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: JobsTable
      - LambdaInvokePolicy:
          FunctionName:
            Ref: WorkerFunction
      Events:
        ForgeApi:
          Type: Api
          Properties:
            Path: /forge
            Method: post
    Metadata:
      SamResourceId: ForgeFunction
  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: WorkerFunction
      Handler: app.lambda_handler
      Timeout: 900
      MemorySize: 1024
      Environment:
        Variables:
          JOBS_TABLE_NAME:
            Ref: JobsTable
          PRODUCT_DB_BUCKET: ad-forge-database-amg-2025
          OPENROUTER_API_KEY_PARAM: /ad-forge/openrouter-api-key
          HF_TOKEN_PARAM: /ad-forge/hf-token
          ELEVENLABS_API_KEY_PARAM: /ad-forge/elevenlabs-api-key
          SHOTSTACK_API_KEY_PARAM: /ad-forge/shotstack-api-key
      Policies:
      - S3ReadPolicy:
          BucketName: ad-forge-database-amg-2025
      - S3WritePolicy:
          BucketName: ad-forge-database-amg-2025
      - DynamoDBCrudPolicy:
          TableName:
            Ref: JobsTable
      - Statement:
        - Effect: Allow
          Action:
          - ssm:GetParameter
          Resource:
          - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ad-forge/openrouter-api-key
          - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ad-forge/hf-token
          - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ad-forge/elevenlabs-api-key
          - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ad-forge/shotstack-api-key
    Metadata:
      SamResourceId: WorkerFunction
  StatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: StatusFunction
      Handler: app.lambda_handler
      Timeout: 29
      MemorySize: 256
      Environment:
        Variables:
          JOBS_TABLE_NAME:
            Ref: JobsTable
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: JobsTable
      Events:
        StatusApi:
          Type: Api
          Properties:
            Path: /status/{jobId}
            Method: get
    Metadata:
      SamResourceId: StatusFunction
Outputs:
  AdForgeApi:
    Description: API Gateway base endpoint URL for the Ad-Forge service
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
